// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';




                abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
                  RustLibApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ManpasikEnginePtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEnginePtr;



                  @protected ManpasikEngine dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine(dynamic raw);

@protected ManpasikEngine dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine(dynamic raw);

@protected String dco_decode_String(dynamic raw);

@protected AiAnalysisResultDto dco_decode_ai_analysis_result_dto(dynamic raw);

@protected bool dco_decode_bool(dynamic raw);

@protected CartridgeInfoDto dco_decode_cartridge_info_dto(dynamic raw);

@protected DeviceInfoDto dco_decode_device_info_dto(dynamic raw);

@protected DifferentialCorrectionDto dco_decode_differential_correction_dto(dynamic raw);

@protected double dco_decode_f_32(dynamic raw);

@protected double dco_decode_f_64(dynamic raw);

@protected FingerprintDto dco_decode_fingerprint_dto(dynamic raw);

@protected int dco_decode_i_8(dynamic raw);

@protected List<String> dco_decode_list_String(dynamic raw);

@protected List<DeviceInfoDto> dco_decode_list_device_info_dto(dynamic raw);

@protected List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

@protected Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

@protected List<double> dco_decode_list_prim_f_64_loose(dynamic raw);

@protected Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

@protected List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected MeasurementPipelineDto dco_decode_measurement_pipeline_dto(dynamic raw);

@protected int dco_decode_u_32(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected void dco_decode_unit(dynamic raw);

@protected BigInt dco_decode_usize(dynamic raw);

@protected ManpasikEngine sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine(SseDeserializer deserializer);

@protected ManpasikEngine sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine(SseDeserializer deserializer);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected AiAnalysisResultDto sse_decode_ai_analysis_result_dto(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected CartridgeInfoDto sse_decode_cartridge_info_dto(SseDeserializer deserializer);

@protected DeviceInfoDto sse_decode_device_info_dto(SseDeserializer deserializer);

@protected DifferentialCorrectionDto sse_decode_differential_correction_dto(SseDeserializer deserializer);

@protected double sse_decode_f_32(SseDeserializer deserializer);

@protected double sse_decode_f_64(SseDeserializer deserializer);

@protected FingerprintDto sse_decode_fingerprint_dto(SseDeserializer deserializer);

@protected int sse_decode_i_8(SseDeserializer deserializer);

@protected List<String> sse_decode_list_String(SseDeserializer deserializer);

@protected List<DeviceInfoDto> sse_decode_list_device_info_dto(SseDeserializer deserializer);

@protected List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

@protected Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

@protected List<double> sse_decode_list_prim_f_64_loose(SseDeserializer deserializer);

@protected Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

@protected List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected MeasurementPipelineDto sse_decode_measurement_pipeline_dto(SseDeserializer deserializer);

@protected int sse_decode_u_32(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected BigInt sse_decode_usize(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine(ManpasikEngine self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine(ManpasikEngine self, SseSerializer serializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_ai_analysis_result_dto(AiAnalysisResultDto self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_cartridge_info_dto(CartridgeInfoDto self, SseSerializer serializer);

@protected void sse_encode_device_info_dto(DeviceInfoDto self, SseSerializer serializer);

@protected void sse_encode_differential_correction_dto(DifferentialCorrectionDto self, SseSerializer serializer);

@protected void sse_encode_f_32(double self, SseSerializer serializer);

@protected void sse_encode_f_64(double self, SseSerializer serializer);

@protected void sse_encode_fingerprint_dto(FingerprintDto self, SseSerializer serializer);

@protected void sse_encode_i_8(int self, SseSerializer serializer);

@protected void sse_encode_list_String(List<String> self, SseSerializer serializer);

@protected void sse_encode_list_device_info_dto(List<DeviceInfoDto> self, SseSerializer serializer);

@protected void sse_encode_list_prim_f_32_loose(List<double> self, SseSerializer serializer);

@protected void sse_encode_list_prim_f_32_strict(Float32List self, SseSerializer serializer);

@protected void sse_encode_list_prim_f_64_loose(List<double> self, SseSerializer serializer);

@protected void sse_encode_list_prim_f_64_strict(Float64List self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_measurement_pipeline_dto(MeasurementPipelineDto self, SseSerializer serializer);

@protected void sse_encode_u_32(int self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);

@protected void sse_encode_usize(BigInt self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);
                }
                


// Section: wire_class


        class RustLibWire implements BaseWire {

            factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
              RustLibWire(lib.ffiDynamicLibrary);
        
            /// Holds the symbol lookup function.
            final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                _lookup;
  
            /// The symbols are looked up in [dynamicLibrary].
            RustLibWire(ffi.DynamicLibrary dynamicLibrary)
                : _lookup = dynamicLibrary.lookup;

            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEnginePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_manpasik_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEnginePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEnginePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_manpasik_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEnginePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
        }
        