// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


                /// Main entrypoint of the Rust API
                class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
                  @internal
                  static final instance = RustLib._();

                  RustLib._();

                  /// Initialize flutter_rust_bridge
                  static Future<void> init({
                    RustLibApi? api,
                    BaseHandler? handler,
                    ExternalLibrary? externalLibrary,
                    bool forceSameCodegenVersion = true,
                  }) async {
                    await instance.initImpl(
                      api: api,
                      handler: handler,
                      externalLibrary: externalLibrary,
                      forceSameCodegenVersion: forceSameCodegenVersion,
                    );
                  }

                  /// Initialize flutter_rust_bridge in mock mode.
                  /// No libraries for FFI are loaded.
                  static void initMock({
                    required RustLibApi api,
                  }) {
                    instance.initMockImpl(
                      api: api,
                    );
                  }

                  /// Dispose flutter_rust_bridge
                  ///
                  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
                  /// is automatically disposed when the app stops.
                  static void dispose() => instance.disposeImpl();

                  @override
                  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

                  @override
                  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

                  @override
                  Future<void> executeRustInitializers() async {
                    
                  }

                  @override
                  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

                  @override
                  String get codegenVersion => '2.12.0';

                  @override
                  int get rustContentHash => 388022629;

                  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
                    stem: 'flutter_bridge',
                    ioDirectory: '../../rust-core/flutter-bridge/target/release/',
                    webPrefix: 'pkg/',
                    wasmBindgenName: 'wasm_bindgen',
                  );
                }
                

                abstract class RustLibApi extends BaseApi {
                  ManpasikEngine crateManpasikEngineNew({required BigInt numChannels });

ManpasikEngine crateManpasikEngineWith1792Channels();

ManpasikEngine crateManpasikEngineWith88Channels();

ManpasikEngine crateManpasikEngineWith896Channels();

Future<AiAnalysisResultDto> crateAnalyzeMeasurement({required double value , required String biomarker });

Future<bool> crateBleConnect({required String deviceId });

String crateBleConnectionQuality({required int rssi });

Future<int> crateBleReadBattery({required String deviceId });

Future<List<DeviceInfoDto>> crateBleScan();

String crateCalculateSha256({required List<int> data });

FingerprintDto crateCreateFingerprint1792({required List<double> data });

FingerprintDto crateCreateFingerprint88({required List<double> data });

FingerprintDto crateCreateFingerprint896({required List<double> data });

Float64List crateDifferentialMeasure({required List<double> sDet , required List<double> sRef , required double alpha });

DifferentialCorrectionDto crateDifferentialMeasureSingle({required double sDet , required double sRef , required double alpha });

double crateFingerprintCosineSimilarity({required List<double> fp1Data , required List<double> fp2Data , required BigInt dimension });

String crateGetEngineVersion();

BigInt crateGetMaxChannels();

Future<CartridgeInfoDto> crateNfcReadCartridge();

Future<MeasurementPipelineDto> crateRunMeasurementPipeline({required List<double> sDet , required List<double> sRef , required double alpha , required String biomarker , required String unit });

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_ManpasikEngine;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_ManpasikEngine;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ManpasikEnginePtr;


                }
                

                class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
                  RustLibApiImpl({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  @override ManpasikEngine crateManpasikEngineNew({required BigInt numChannels })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_usize(numChannels, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateManpasikEngineNewConstMeta,
            argValues: [numChannels],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateManpasikEngineNewConstMeta => const TaskConstMeta(
            debugName: "ManpasikEngine_new",
            argNames: ["numChannels"],
        );
        

@override ManpasikEngine crateManpasikEngineWith1792Channels()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateManpasikEngineWith1792ChannelsConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateManpasikEngineWith1792ChannelsConstMeta => const TaskConstMeta(
            debugName: "ManpasikEngine_with_1792_channels",
            argNames: [],
        );
        

@override ManpasikEngine crateManpasikEngineWith88Channels()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateManpasikEngineWith88ChannelsConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateManpasikEngineWith88ChannelsConstMeta => const TaskConstMeta(
            debugName: "ManpasikEngine_with_88_channels",
            argNames: [],
        );
        

@override ManpasikEngine crateManpasikEngineWith896Channels()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateManpasikEngineWith896ChannelsConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateManpasikEngineWith896ChannelsConstMeta => const TaskConstMeta(
            debugName: "ManpasikEngine_with_896_channels",
            argNames: [],
        );
        

@override Future<AiAnalysisResultDto> crateAnalyzeMeasurement({required double value , required String biomarker })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_f_64(value, serializer);
sse_encode_String(biomarker, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_ai_analysis_result_dto,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateAnalyzeMeasurementConstMeta,
            argValues: [value, biomarker],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateAnalyzeMeasurementConstMeta => const TaskConstMeta(
            debugName: "analyze_measurement",
            argNames: ["value", "biomarker"],
        );
        

@override Future<bool> crateBleConnect({required String deviceId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(deviceId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        )
        ,
            constMeta: kCrateBleConnectConstMeta,
            argValues: [deviceId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateBleConnectConstMeta => const TaskConstMeta(
            debugName: "ble_connect",
            argNames: ["deviceId"],
        );
        

@override String crateBleConnectionQuality({required int rssi })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_i_8(rssi, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateBleConnectionQualityConstMeta,
            argValues: [rssi],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateBleConnectionQualityConstMeta => const TaskConstMeta(
            debugName: "ble_connection_quality",
            argNames: ["rssi"],
        );
        

@override Future<int> crateBleReadBattery({required String deviceId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(deviceId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_u_8,
          decodeErrorData: sse_decode_String,
        )
        ,
            constMeta: kCrateBleReadBatteryConstMeta,
            argValues: [deviceId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateBleReadBatteryConstMeta => const TaskConstMeta(
            debugName: "ble_read_battery",
            argNames: ["deviceId"],
        );
        

@override Future<List<DeviceInfoDto>> crateBleScan()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_device_info_dto,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateBleScanConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateBleScanConstMeta => const TaskConstMeta(
            debugName: "ble_scan",
            argNames: [],
        );
        

@override String crateCalculateSha256({required List<int> data })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_list_prim_u_8_loose(data, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateCalculateSha256ConstMeta,
            argValues: [data],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateCalculateSha256ConstMeta => const TaskConstMeta(
            debugName: "calculate_sha256",
            argNames: ["data"],
        );
        

@override FingerprintDto crateCreateFingerprint1792({required List<double> data })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_list_prim_f_32_loose(data, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_fingerprint_dto,
          decodeErrorData: sse_decode_String,
        )
        ,
            constMeta: kCrateCreateFingerprint1792ConstMeta,
            argValues: [data],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateCreateFingerprint1792ConstMeta => const TaskConstMeta(
            debugName: "create_fingerprint_1792",
            argNames: ["data"],
        );
        

@override FingerprintDto crateCreateFingerprint88({required List<double> data })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_list_prim_f_32_loose(data, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_fingerprint_dto,
          decodeErrorData: sse_decode_String,
        )
        ,
            constMeta: kCrateCreateFingerprint88ConstMeta,
            argValues: [data],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateCreateFingerprint88ConstMeta => const TaskConstMeta(
            debugName: "create_fingerprint_88",
            argNames: ["data"],
        );
        

@override FingerprintDto crateCreateFingerprint896({required List<double> data })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_list_prim_f_32_loose(data, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_fingerprint_dto,
          decodeErrorData: sse_decode_String,
        )
        ,
            constMeta: kCrateCreateFingerprint896ConstMeta,
            argValues: [data],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateCreateFingerprint896ConstMeta => const TaskConstMeta(
            debugName: "create_fingerprint_896",
            argNames: ["data"],
        );
        

@override Float64List crateDifferentialMeasure({required List<double> sDet , required List<double> sRef , required double alpha })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_list_prim_f_64_loose(sDet, serializer);
sse_encode_list_prim_f_64_loose(sRef, serializer);
sse_encode_f_64(alpha, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: sse_decode_String,
        )
        ,
            constMeta: kCrateDifferentialMeasureConstMeta,
            argValues: [sDet, sRef, alpha],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateDifferentialMeasureConstMeta => const TaskConstMeta(
            debugName: "differential_measure",
            argNames: ["sDet", "sRef", "alpha"],
        );
        

@override DifferentialCorrectionDto crateDifferentialMeasureSingle({required double sDet , required double sRef , required double alpha })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_f_64(sDet, serializer);
sse_encode_f_64(sRef, serializer);
sse_encode_f_64(alpha, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_differential_correction_dto,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateDifferentialMeasureSingleConstMeta,
            argValues: [sDet, sRef, alpha],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateDifferentialMeasureSingleConstMeta => const TaskConstMeta(
            debugName: "differential_measure_single",
            argNames: ["sDet", "sRef", "alpha"],
        );
        

@override double crateFingerprintCosineSimilarity({required List<double> fp1Data , required List<double> fp2Data , required BigInt dimension })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_list_prim_f_32_loose(fp1Data, serializer);
sse_encode_list_prim_f_32_loose(fp2Data, serializer);
sse_encode_usize(dimension, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: sse_decode_String,
        )
        ,
            constMeta: kCrateFingerprintCosineSimilarityConstMeta,
            argValues: [fp1Data, fp2Data, dimension],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateFingerprintCosineSimilarityConstMeta => const TaskConstMeta(
            debugName: "fingerprint_cosine_similarity",
            argNames: ["fp1Data", "fp2Data", "dimension"],
        );
        

@override String crateGetEngineVersion()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateGetEngineVersionConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGetEngineVersionConstMeta => const TaskConstMeta(
            debugName: "get_engine_version",
            argNames: [],
        );
        

@override BigInt crateGetMaxChannels()  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateGetMaxChannelsConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGetMaxChannelsConstMeta => const TaskConstMeta(
            debugName: "get_max_channels",
            argNames: [],
        );
        

@override Future<CartridgeInfoDto> crateNfcReadCartridge()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_cartridge_info_dto,
          decodeErrorData: sse_decode_String,
        )
        ,
            constMeta: kCrateNfcReadCartridgeConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateNfcReadCartridgeConstMeta => const TaskConstMeta(
            debugName: "nfc_read_cartridge",
            argNames: [],
        );
        

@override Future<MeasurementPipelineDto> crateRunMeasurementPipeline({required List<double> sDet , required List<double> sRef , required double alpha , required String biomarker , required String unit })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_list_prim_f_64_loose(sDet, serializer);
sse_encode_list_prim_f_64_loose(sRef, serializer);
sse_encode_f_64(alpha, serializer);
sse_encode_String(biomarker, serializer);
sse_encode_String(unit, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_measurement_pipeline_dto,
          decodeErrorData: sse_decode_String,
        )
        ,
            constMeta: kCrateRunMeasurementPipelineConstMeta,
            argValues: [sDet, sRef, alpha, biomarker, unit],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateRunMeasurementPipelineConstMeta => const TaskConstMeta(
            debugName: "run_measurement_pipeline",
            argNames: ["sDet", "sRef", "alpha", "biomarker", "unit"],
        );
        

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_ManpasikEngine => wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_ManpasikEngine => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine;



                  @protected ManpasikEngine dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return ManpasikEngineImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected ManpasikEngine dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return ManpasikEngineImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected String dco_decode_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as String; }

@protected AiAnalysisResultDto dco_decode_ai_analysis_result_dto(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 5) throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
                return AiAnalysisResultDto(riskLevel: dco_decode_String(arr[0]),
healthScore: dco_decode_f_64(arr[1]),
summary: dco_decode_String(arr[2]),
recommendations: dco_decode_list_String(arr[3]),
trend: dco_decode_String(arr[4]),); }

@protected bool dco_decode_bool(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as bool; }

@protected CartridgeInfoDto dco_decode_cartridge_info_dto(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 5) throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
                return CartridgeInfoDto(cartridgeId: dco_decode_String(arr[0]),
cartridgeType: dco_decode_String(arr[1]),
lotId: dco_decode_String(arr[2]),
expiryDate: dco_decode_String(arr[3]),
remainingUses: dco_decode_u_32(arr[4]),); }

@protected DeviceInfoDto dco_decode_device_info_dto(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
                return DeviceInfoDto(deviceId: dco_decode_String(arr[0]),
name: dco_decode_String(arr[1]),
rssi: dco_decode_i_8(arr[2]),
state: dco_decode_String(arr[3]),); }

@protected DifferentialCorrectionDto dco_decode_differential_correction_dto(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
                return DifferentialCorrectionDto(sDet: dco_decode_f_64(arr[0]),
sRef: dco_decode_f_64(arr[1]),
alpha: dco_decode_f_64(arr[2]),
sCorrected: dco_decode_f_64(arr[3]),); }

@protected double dco_decode_f_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as double; }

@protected double dco_decode_f_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as double; }

@protected FingerprintDto dco_decode_fingerprint_dto(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
                return FingerprintDto(data: dco_decode_list_prim_f_32_strict(arr[0]),
dimension: dco_decode_usize(arr[1]),
measurementType: dco_decode_String(arr[2]),
normalized: dco_decode_bool(arr[3]),); }

@protected int dco_decode_i_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected List<String> dco_decode_list_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_String).toList(); }

@protected List<DeviceInfoDto> dco_decode_list_device_info_dto(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_device_info_dto).toList(); }

@protected List<double> dco_decode_list_prim_f_32_loose(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as List<double>; }

@protected Float32List dco_decode_list_prim_f_32_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Float32List; }

@protected List<double> dco_decode_list_prim_f_64_loose(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as List<double>; }

@protected Float64List dco_decode_list_prim_f_64_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Float64List; }

@protected List<int> dco_decode_list_prim_u_8_loose(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as List<int>; }

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Uint8List; }

@protected MeasurementPipelineDto dco_decode_measurement_pipeline_dto(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 11) throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
                return MeasurementPipelineDto(primaryValue: dco_decode_f_64(arr[0]),
referenceValue: dco_decode_f_64(arr[1]),
differentialValue: dco_decode_f_64(arr[2]),
snr: dco_decode_f_64(arr[3]),
confidence: dco_decode_f_64(arr[4]),
biomarker: dco_decode_String(arr[5]),
unit: dco_decode_String(arr[6]),
riskLevel: dco_decode_String(arr[7]),
healthScore: dco_decode_f_64(arr[8]),
recommendations: dco_decode_list_String(arr[9]),
pipelineDurationMs: dco_decode_f_64(arr[10]),); }

@protected int dco_decode_u_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected int dco_decode_u_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected void dco_decode_unit(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return; }

@protected BigInt dco_decode_usize(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeU64(raw); }

@protected ManpasikEngine sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return ManpasikEngineImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected ManpasikEngine sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return ManpasikEngineImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected String sse_decode_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_list_prim_u_8_strict(deserializer);
        return utf8.decoder.convert(inner); }

@protected AiAnalysisResultDto sse_decode_ai_analysis_result_dto(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_riskLevel = sse_decode_String(deserializer);
var var_healthScore = sse_decode_f_64(deserializer);
var var_summary = sse_decode_String(deserializer);
var var_recommendations = sse_decode_list_String(deserializer);
var var_trend = sse_decode_String(deserializer);
return AiAnalysisResultDto(riskLevel: var_riskLevel, healthScore: var_healthScore, summary: var_summary, recommendations: var_recommendations, trend: var_trend); }

@protected bool sse_decode_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8() != 0; }

@protected CartridgeInfoDto sse_decode_cartridge_info_dto(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_cartridgeId = sse_decode_String(deserializer);
var var_cartridgeType = sse_decode_String(deserializer);
var var_lotId = sse_decode_String(deserializer);
var var_expiryDate = sse_decode_String(deserializer);
var var_remainingUses = sse_decode_u_32(deserializer);
return CartridgeInfoDto(cartridgeId: var_cartridgeId, cartridgeType: var_cartridgeType, lotId: var_lotId, expiryDate: var_expiryDate, remainingUses: var_remainingUses); }

@protected DeviceInfoDto sse_decode_device_info_dto(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_deviceId = sse_decode_String(deserializer);
var var_name = sse_decode_String(deserializer);
var var_rssi = sse_decode_i_8(deserializer);
var var_state = sse_decode_String(deserializer);
return DeviceInfoDto(deviceId: var_deviceId, name: var_name, rssi: var_rssi, state: var_state); }

@protected DifferentialCorrectionDto sse_decode_differential_correction_dto(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_sDet = sse_decode_f_64(deserializer);
var var_sRef = sse_decode_f_64(deserializer);
var var_alpha = sse_decode_f_64(deserializer);
var var_sCorrected = sse_decode_f_64(deserializer);
return DifferentialCorrectionDto(sDet: var_sDet, sRef: var_sRef, alpha: var_alpha, sCorrected: var_sCorrected); }

@protected double sse_decode_f_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getFloat32(); }

@protected double sse_decode_f_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getFloat64(); }

@protected FingerprintDto sse_decode_fingerprint_dto(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_data = sse_decode_list_prim_f_32_strict(deserializer);
var var_dimension = sse_decode_usize(deserializer);
var var_measurementType = sse_decode_String(deserializer);
var var_normalized = sse_decode_bool(deserializer);
return FingerprintDto(data: var_data, dimension: var_dimension, measurementType: var_measurementType, normalized: var_normalized); }

@protected int sse_decode_i_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getInt8(); }

@protected List<String> sse_decode_list_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <String>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_String(deserializer)); }
        return ans_;
         }

@protected List<DeviceInfoDto> sse_decode_list_device_info_dto(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <DeviceInfoDto>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_device_info_dto(deserializer)); }
        return ans_;
         }

@protected List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getFloat32List(len_); }

@protected Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getFloat32List(len_); }

@protected List<double> sse_decode_list_prim_f_64_loose(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getFloat64List(len_); }

@protected Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getFloat64List(len_); }

@protected List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected MeasurementPipelineDto sse_decode_measurement_pipeline_dto(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_primaryValue = sse_decode_f_64(deserializer);
var var_referenceValue = sse_decode_f_64(deserializer);
var var_differentialValue = sse_decode_f_64(deserializer);
var var_snr = sse_decode_f_64(deserializer);
var var_confidence = sse_decode_f_64(deserializer);
var var_biomarker = sse_decode_String(deserializer);
var var_unit = sse_decode_String(deserializer);
var var_riskLevel = sse_decode_String(deserializer);
var var_healthScore = sse_decode_f_64(deserializer);
var var_recommendations = sse_decode_list_String(deserializer);
var var_pipelineDurationMs = sse_decode_f_64(deserializer);
return MeasurementPipelineDto(primaryValue: var_primaryValue, referenceValue: var_referenceValue, differentialValue: var_differentialValue, snr: var_snr, confidence: var_confidence, biomarker: var_biomarker, unit: var_unit, riskLevel: var_riskLevel, healthScore: var_healthScore, recommendations: var_recommendations, pipelineDurationMs: var_pipelineDurationMs); }

@protected int sse_decode_u_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint32(); }

@protected int sse_decode_u_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8(); }

@protected void sse_decode_unit(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected BigInt sse_decode_usize(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getBigUint64(); }

@protected int sse_decode_i_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getInt32(); }

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine(ManpasikEngine self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as ManpasikEngineImpl).frbInternalSseEncode(move: true), serializer); }

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerManpasikEngine(ManpasikEngine self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as ManpasikEngineImpl).frbInternalSseEncode(move: null), serializer); }

@protected void sse_encode_String(String self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer); }

@protected void sse_encode_ai_analysis_result_dto(AiAnalysisResultDto self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.riskLevel, serializer);
sse_encode_f_64(self.healthScore, serializer);
sse_encode_String(self.summary, serializer);
sse_encode_list_String(self.recommendations, serializer);
sse_encode_String(self.trend, serializer);
 }

@protected void sse_encode_bool(bool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self ? 1 : 0); }

@protected void sse_encode_cartridge_info_dto(CartridgeInfoDto self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.cartridgeId, serializer);
sse_encode_String(self.cartridgeType, serializer);
sse_encode_String(self.lotId, serializer);
sse_encode_String(self.expiryDate, serializer);
sse_encode_u_32(self.remainingUses, serializer);
 }

@protected void sse_encode_device_info_dto(DeviceInfoDto self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.deviceId, serializer);
sse_encode_String(self.name, serializer);
sse_encode_i_8(self.rssi, serializer);
sse_encode_String(self.state, serializer);
 }

@protected void sse_encode_differential_correction_dto(DifferentialCorrectionDto self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_f_64(self.sDet, serializer);
sse_encode_f_64(self.sRef, serializer);
sse_encode_f_64(self.alpha, serializer);
sse_encode_f_64(self.sCorrected, serializer);
 }

@protected void sse_encode_f_32(double self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putFloat32(self); }

@protected void sse_encode_f_64(double self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putFloat64(self); }

@protected void sse_encode_fingerprint_dto(FingerprintDto self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_f_32_strict(self.data, serializer);
sse_encode_usize(self.dimension, serializer);
sse_encode_String(self.measurementType, serializer);
sse_encode_bool(self.normalized, serializer);
 }

@protected void sse_encode_i_8(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putInt8(self); }

@protected void sse_encode_list_String(List<String> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_String(item, serializer); } }

@protected void sse_encode_list_device_info_dto(List<DeviceInfoDto> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_device_info_dto(item, serializer); } }

@protected void sse_encode_list_prim_f_32_loose(List<double> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putFloat32List(self is Float32List ? self : Float32List.fromList(self)); }

@protected void sse_encode_list_prim_f_32_strict(Float32List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putFloat32List(self); }

@protected void sse_encode_list_prim_f_64_loose(List<double> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putFloat64List(self is Float64List ? self : Float64List.fromList(self)); }

@protected void sse_encode_list_prim_f_64_strict(Float64List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putFloat64List(self); }

@protected void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self is Uint8List ? self : Uint8List.fromList(self)); }

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self); }

@protected void sse_encode_measurement_pipeline_dto(MeasurementPipelineDto self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_f_64(self.primaryValue, serializer);
sse_encode_f_64(self.referenceValue, serializer);
sse_encode_f_64(self.differentialValue, serializer);
sse_encode_f_64(self.snr, serializer);
sse_encode_f_64(self.confidence, serializer);
sse_encode_String(self.biomarker, serializer);
sse_encode_String(self.unit, serializer);
sse_encode_String(self.riskLevel, serializer);
sse_encode_f_64(self.healthScore, serializer);
sse_encode_list_String(self.recommendations, serializer);
sse_encode_f_64(self.pipelineDurationMs, serializer);
 }

@protected void sse_encode_u_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint32(self); }

@protected void sse_encode_u_8(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self); }

@protected void sse_encode_unit(void self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected void sse_encode_usize(BigInt self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putBigUint64(self); }

@protected void sse_encode_i_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putInt32(self); }
                }
                

            @sealed class ManpasikEngineImpl extends RustOpaque implements ManpasikEngine {
                // Not to be used by end users
                ManpasikEngineImpl.frbInternalDcoDecode(List<dynamic> wire):
                    super.frbInternalDcoDecode(wire, _kStaticData);

                // Not to be used by end users
                ManpasikEngineImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative):
                    super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

                static final _kStaticData = RustArcStaticData(
                    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_ManpasikEngine,
                    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_ManpasikEngine,
                    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_ManpasikEnginePtr,
                );

                
            }