// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'lib.freezed.dart';

            

            /// 차동측정 수행
Float64List  differentialMeasure({required List<double> sDet , required List<double> sRef , required double alpha }) => RustLib.instance.api.crateDifferentialMeasure(sDet: sDet, sRef: sRef, alpha: alpha);

/// 단일 채널 차동측정
DifferentialCorrectionDto  differentialMeasureSingle({required double sDet , required double sRef , required double alpha }) => RustLib.instance.api.crateDifferentialMeasureSingle(sDet: sDet, sRef: sRef, alpha: alpha);

/// 핑거프린트 벡터 생성 (88차원)
FingerprintDto  createFingerprint88({required List<double> data }) => RustLib.instance.api.crateCreateFingerprint88(data: data);

/// 핑거프린트 벡터 생성 (896차원)
FingerprintDto  createFingerprint896({required List<double> data }) => RustLib.instance.api.crateCreateFingerprint896(data: data);

/// 핑거프린트 벡터 생성 (1792차원, Phase 5 궁극 확장)
FingerprintDto  createFingerprint1792({required List<double> data }) => RustLib.instance.api.crateCreateFingerprint1792(data: data);

/// 코사인 유사도 계산
double  fingerprintCosineSimilarity({required List<double> fp1Data , required List<double> fp2Data , required BigInt dimension }) => RustLib.instance.api.crateFingerprintCosineSimilarity(fp1Data: fp1Data, fp2Data: fp2Data, dimension: dimension);

/// BLE 디바이스 스캔
Future<List<DeviceInfoDto>>  bleScan() => RustLib.instance.api.crateBleScan();

/// BLE 디바이스 연결
Future<bool>  bleConnect({required String deviceId }) => RustLib.instance.api.crateBleConnect(deviceId: deviceId);

/// 카트리지 읽기
Future<CartridgeInfoDto>  nfcReadCartridge() => RustLib.instance.api.crateNfcReadCartridge();

/// 차동 계측 수행 + AI 안전 검증 파이프라인
Future<MeasurementPipelineDto>  runMeasurementPipeline({required List<double> sDet , required List<double> sRef , required double alpha , required String biomarker , required String unit }) => RustLib.instance.api.crateRunMeasurementPipeline(sDet: sDet, sRef: sRef, alpha: alpha, biomarker: biomarker, unit: unit);

/// AI 분석만 수행 (측정값 → 위험도 판정)
Future<AiAnalysisResultDto>  analyzeMeasurement({required double value , required String biomarker }) => RustLib.instance.api.crateAnalyzeMeasurement(value: value, biomarker: biomarker);

/// BLE 배터리 레벨 읽기
Future<int>  bleReadBattery({required String deviceId }) => RustLib.instance.api.crateBleReadBattery(deviceId: deviceId);

/// BLE 연결 품질 조회
String  bleConnectionQuality({required int rssi }) => RustLib.instance.api.crateBleConnectionQuality(rssi: rssi);

/// 엔진 버전 조회
String  getEngineVersion() => RustLib.instance.api.crateGetEngineVersion();

/// 최대 채널 수 조회
BigInt  getMaxChannels() => RustLib.instance.api.crateGetMaxChannels();

/// SHA-256 해시 계산
String  calculateSha256({required List<int> data }) => RustLib.instance.api.crateCalculateSha256(data: data);

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ManpasikEngine>>
                abstract class ManpasikEngine implements RustOpaqueInterface {
                    /// 새 엔진 인스턴스 생성
factory ManpasikEngine({required BigInt numChannels })=>RustLib.instance.api.crateManpasikEngineNew(numChannels: numChannels);


/// 1792차원 궁극 엔진 생성 (Phase 5: E12-IF + 시간축 확장)
static ManpasikEngine  with1792Channels()=>RustLib.instance.api.crateManpasikEngineWith1792Channels();


/// 88차원 기본 엔진 생성
static ManpasikEngine  with88Channels()=>RustLib.instance.api.crateManpasikEngineWith88Channels();


/// 896차원 완전 엔진 생성
static ManpasikEngine  with896Channels()=>RustLib.instance.api.crateManpasikEngineWith896Channels();



                    
                }
                

/// AI 분석 결과 DTO
@freezed
sealed class AiAnalysisResultDto with _$AiAnalysisResultDto  {
                
                const factory AiAnalysisResultDto({ required  String riskLevel, required  double healthScore, required  String summary, required  List<String> recommendations, required  String trend,}) = _AiAnalysisResultDto;
                
                
                
            }

/// 카트리지 정보 DTO
@freezed
sealed class CartridgeInfoDto with _$CartridgeInfoDto  {
                
                const factory CartridgeInfoDto({ required  String cartridgeId, required  String cartridgeType, required  String lotId, required  String expiryDate, required  int remainingUses,}) = _CartridgeInfoDto;
                
                
                
            }

/// 디바이스 정보 DTO
@freezed
sealed class DeviceInfoDto with _$DeviceInfoDto  {
                
                const factory DeviceInfoDto({ required  String deviceId, required  String name, required  int rssi, required  String state,}) = _DeviceInfoDto;
                
                
                
            }

/// 차동측정 결과 DTO (Flutter 전달용)
@freezed
sealed class DifferentialCorrectionDto with _$DifferentialCorrectionDto  {
                
                const factory DifferentialCorrectionDto({ required  double sDet, required  double sRef, required  double alpha, required  double sCorrected,}) = _DifferentialCorrectionDto;
                
                
                
            }

/// 핑거프린트 DTO
@freezed
sealed class FingerprintDto with _$FingerprintDto  {
                
                const factory FingerprintDto({ required  Float32List data, required  BigInt dimension, required  String measurementType, required  bool normalized,}) = _FingerprintDto;
                
                
                
            }

/// 측정 파이프라인 결과 DTO
@freezed
sealed class MeasurementPipelineDto with _$MeasurementPipelineDto  {
                
                const factory MeasurementPipelineDto({ required  double primaryValue, required  double referenceValue, required  double differentialValue, required  double snr, required  double confidence, required  String biomarker, required  String unit, required  String riskLevel, required  double healthScore, required  List<String> recommendations, required  double pipelineDurationMs,}) = _MeasurementPipelineDto;
                
                
                
            }
            