// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: health.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServingStatus int32

const (
	ServingStatus_SERVING_STATUS_UNKNOWN         ServingStatus = 0
	ServingStatus_SERVING_STATUS_SERVING         ServingStatus = 1
	ServingStatus_SERVING_STATUS_NOT_SERVING     ServingStatus = 2
	ServingStatus_SERVING_STATUS_SERVICE_UNKNOWN ServingStatus = 3 // Watch에서만 사용
)

// Enum value maps for ServingStatus.
var (
	ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNKNOWN",
		1: "SERVING_STATUS_SERVING",
		2: "SERVING_STATUS_NOT_SERVING",
		3: "SERVING_STATUS_SERVICE_UNKNOWN",
	}
	ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNKNOWN":         0,
		"SERVING_STATUS_SERVING":         1,
		"SERVING_STATUS_NOT_SERVING":     2,
		"SERVING_STATUS_SERVICE_UNKNOWN": 3,
	}
)

func (x ServingStatus) Enum() *ServingStatus {
	p := new(ServingStatus)
	*p = x
	return p
}

func (x ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_health_proto_enumTypes[0].Descriptor()
}

func (ServingStatus) Type() protoreflect.EnumType {
	return &file_health_proto_enumTypes[0]
}

func (x ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServingStatus.Descriptor instead.
func (ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

type DependencyType int32

const (
	DependencyType_DEPENDENCY_TYPE_UNKNOWN          DependencyType = 0
	DependencyType_DEPENDENCY_TYPE_DATABASE         DependencyType = 1
	DependencyType_DEPENDENCY_TYPE_CACHE            DependencyType = 2
	DependencyType_DEPENDENCY_TYPE_MESSAGE_QUEUE    DependencyType = 3
	DependencyType_DEPENDENCY_TYPE_EXTERNAL_SERVICE DependencyType = 4
	DependencyType_DEPENDENCY_TYPE_STORAGE          DependencyType = 5
	DependencyType_DEPENDENCY_TYPE_SEARCH           DependencyType = 6
)

// Enum value maps for DependencyType.
var (
	DependencyType_name = map[int32]string{
		0: "DEPENDENCY_TYPE_UNKNOWN",
		1: "DEPENDENCY_TYPE_DATABASE",
		2: "DEPENDENCY_TYPE_CACHE",
		3: "DEPENDENCY_TYPE_MESSAGE_QUEUE",
		4: "DEPENDENCY_TYPE_EXTERNAL_SERVICE",
		5: "DEPENDENCY_TYPE_STORAGE",
		6: "DEPENDENCY_TYPE_SEARCH",
	}
	DependencyType_value = map[string]int32{
		"DEPENDENCY_TYPE_UNKNOWN":          0,
		"DEPENDENCY_TYPE_DATABASE":         1,
		"DEPENDENCY_TYPE_CACHE":            2,
		"DEPENDENCY_TYPE_MESSAGE_QUEUE":    3,
		"DEPENDENCY_TYPE_EXTERNAL_SERVICE": 4,
		"DEPENDENCY_TYPE_STORAGE":          5,
		"DEPENDENCY_TYPE_SEARCH":           6,
	}
)

func (x DependencyType) Enum() *DependencyType {
	p := new(DependencyType)
	*p = x
	return p
}

func (x DependencyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DependencyType) Descriptor() protoreflect.EnumDescriptor {
	return file_health_proto_enumTypes[1].Descriptor()
}

func (DependencyType) Type() protoreflect.EnumType {
	return &file_health_proto_enumTypes[1]
}

func (x DependencyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DependencyType.Descriptor instead.
func (DependencyType) EnumDescriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{1}
}

type DependencyHealth int32

const (
	DependencyHealth_DEPENDENCY_HEALTH_UNKNOWN   DependencyHealth = 0
	DependencyHealth_DEPENDENCY_HEALTH_HEALTHY   DependencyHealth = 1
	DependencyHealth_DEPENDENCY_HEALTH_DEGRADED  DependencyHealth = 2
	DependencyHealth_DEPENDENCY_HEALTH_UNHEALTHY DependencyHealth = 3
)

// Enum value maps for DependencyHealth.
var (
	DependencyHealth_name = map[int32]string{
		0: "DEPENDENCY_HEALTH_UNKNOWN",
		1: "DEPENDENCY_HEALTH_HEALTHY",
		2: "DEPENDENCY_HEALTH_DEGRADED",
		3: "DEPENDENCY_HEALTH_UNHEALTHY",
	}
	DependencyHealth_value = map[string]int32{
		"DEPENDENCY_HEALTH_UNKNOWN":   0,
		"DEPENDENCY_HEALTH_HEALTHY":   1,
		"DEPENDENCY_HEALTH_DEGRADED":  2,
		"DEPENDENCY_HEALTH_UNHEALTHY": 3,
	}
)

func (x DependencyHealth) Enum() *DependencyHealth {
	p := new(DependencyHealth)
	*p = x
	return p
}

func (x DependencyHealth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DependencyHealth) Descriptor() protoreflect.EnumDescriptor {
	return file_health_proto_enumTypes[2].Descriptor()
}

func (DependencyHealth) Type() protoreflect.EnumType {
	return &file_health_proto_enumTypes[2]
}

func (x DependencyHealth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DependencyHealth.Descriptor instead.
func (DependencyHealth) EnumDescriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{2}
}

type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 확인할 서비스 이름 (빈 문자열 = 서버 전체 상태)
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ServingStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=manpasik.health.v1.ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() ServingStatus {
	if x != nil {
		return x.Status
	}
	return ServingStatus_SERVING_STATUS_UNKNOWN
}

type GetStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 포함할 상세 정보
	IncludeMetadata     bool `protobuf:"varint,1,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	IncludeDependencies bool `protobuf:"varint,2,opt,name=include_dependencies,json=includeDependencies,proto3" json:"include_dependencies,omitempty"`
	IncludeMetrics      bool `protobuf:"varint,3,opt,name=include_metrics,json=includeMetrics,proto3" json:"include_metrics,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

func (x *GetStatusRequest) GetIncludeDependencies() bool {
	if x != nil {
		return x.IncludeDependencies
	}
	return false
}

func (x *GetStatusRequest) GetIncludeMetrics() bool {
	if x != nil {
		return x.IncludeMetrics
	}
	return false
}

type GetStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 서비스 정보
	ServiceInfo *ServiceInfo `protobuf:"bytes,1,opt,name=service_info,json=serviceInfo,proto3" json:"service_info,omitempty"`
	// 상태
	Status ServingStatus `protobuf:"varint,2,opt,name=status,proto3,enum=manpasik.health.v1.ServingStatus" json:"status,omitempty"`
	// 메타데이터
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 의존성 상태
	Dependencies []*DependencyStatus `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	// 메트릭
	Metrics       *ServiceMetrics `protobuf:"bytes,5,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetServiceInfo() *ServiceInfo {
	if x != nil {
		return x.ServiceInfo
	}
	return nil
}

func (x *GetStatusResponse) GetStatus() ServingStatus {
	if x != nil {
		return x.Status
	}
	return ServingStatus_SERVING_STATUS_UNKNOWN
}

func (x *GetStatusResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetStatusResponse) GetDependencies() []*DependencyStatus {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *GetStatusResponse) GetMetrics() *ServiceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ServiceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 서비스 이름
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 버전
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// 빌드 시간
	BuildTime string `protobuf:"bytes,3,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	// 빌드 커밋
	BuildCommit string `protobuf:"bytes,4,opt,name=build_commit,json=buildCommit,proto3" json:"build_commit,omitempty"`
	// Go 버전
	GoVersion string `protobuf:"bytes,5,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	// 시작 시간
	StartedAt string `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// 가동 시간 (초)
	UptimeSeconds int64 `protobuf:"varint,7,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceInfo) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *ServiceInfo) GetBuildCommit() string {
	if x != nil {
		return x.BuildCommit
	}
	return ""
}

func (x *ServiceInfo) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *ServiceInfo) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ServiceInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type DependencyStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 의존성 이름 (예: "postgres", "redis", "kafka")
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 의존성 타입
	Type DependencyType `protobuf:"varint,2,opt,name=type,proto3,enum=manpasik.health.v1.DependencyType" json:"type,omitempty"`
	// 상태
	Health DependencyHealth `protobuf:"varint,3,opt,name=health,proto3,enum=manpasik.health.v1.DependencyHealth" json:"health,omitempty"`
	// 응답 시간 (밀리초)
	LatencyMs float32 `protobuf:"fixed32,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// 상세 메시지
	Message       string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyStatus) Reset() {
	*x = DependencyStatus{}
	mi := &file_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyStatus) ProtoMessage() {}

func (x *DependencyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyStatus.ProtoReflect.Descriptor instead.
func (*DependencyStatus) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{5}
}

func (x *DependencyStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DependencyStatus) GetType() DependencyType {
	if x != nil {
		return x.Type
	}
	return DependencyType_DEPENDENCY_TYPE_UNKNOWN
}

func (x *DependencyStatus) GetHealth() DependencyHealth {
	if x != nil {
		return x.Health
	}
	return DependencyHealth_DEPENDENCY_HEALTH_UNKNOWN
}

func (x *DependencyStatus) GetLatencyMs() float32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *DependencyStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServiceMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 활성 연결 수
	ActiveConnections int32 `protobuf:"varint,1,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	// 처리 중인 요청 수
	PendingRequests int32 `protobuf:"varint,2,opt,name=pending_requests,json=pendingRequests,proto3" json:"pending_requests,omitempty"`
	// 에러율 (%)
	ErrorRate float32 `protobuf:"fixed32,3,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	// 평균 응답 시간 (밀리초)
	AvgResponseTimeMs float32 `protobuf:"fixed32,4,opt,name=avg_response_time_ms,json=avgResponseTimeMs,proto3" json:"avg_response_time_ms,omitempty"`
	// 메모리 사용량 (바이트)
	MemoryBytes int64 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	// CPU 사용률 (%)
	CpuUsage float32 `protobuf:"fixed32,6,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	// 고루틴 수
	Goroutines    int32 `protobuf:"varint,7,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceMetrics) Reset() {
	*x = ServiceMetrics{}
	mi := &file_health_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMetrics) ProtoMessage() {}

func (x *ServiceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMetrics.ProtoReflect.Descriptor instead.
func (*ServiceMetrics) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceMetrics) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *ServiceMetrics) GetPendingRequests() int32 {
	if x != nil {
		return x.PendingRequests
	}
	return 0
}

func (x *ServiceMetrics) GetErrorRate() float32 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *ServiceMetrics) GetAvgResponseTimeMs() float32 {
	if x != nil {
		return x.AvgResponseTimeMs
	}
	return 0
}

func (x *ServiceMetrics) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ServiceMetrics) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ServiceMetrics) GetGoroutines() int32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

type CheckDependenciesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 확인할 의존성 목록 (빈 경우 전체 확인)
	DependencyNames []string `protobuf:"bytes,1,rep,name=dependency_names,json=dependencyNames,proto3" json:"dependency_names,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckDependenciesRequest) Reset() {
	*x = CheckDependenciesRequest{}
	mi := &file_health_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDependenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDependenciesRequest) ProtoMessage() {}

func (x *CheckDependenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDependenciesRequest.ProtoReflect.Descriptor instead.
func (*CheckDependenciesRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{7}
}

func (x *CheckDependenciesRequest) GetDependencyNames() []string {
	if x != nil {
		return x.DependencyNames
	}
	return nil
}

type CheckDependenciesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 전체 상태
	AllHealthy bool `protobuf:"varint,1,opt,name=all_healthy,json=allHealthy,proto3" json:"all_healthy,omitempty"`
	// 개별 의존성 상태
	Dependencies  []*DependencyStatus `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDependenciesResponse) Reset() {
	*x = CheckDependenciesResponse{}
	mi := &file_health_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDependenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDependenciesResponse) ProtoMessage() {}

func (x *CheckDependenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDependenciesResponse.ProtoReflect.Descriptor instead.
func (*CheckDependenciesResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{8}
}

func (x *CheckDependenciesResponse) GetAllHealthy() bool {
	if x != nil {
		return x.AllHealthy
	}
	return false
}

func (x *CheckDependenciesResponse) GetDependencies() []*DependencyStatus {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_health_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{9}
}

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_health_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{10}
}

func (x *ReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ReadyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveRequest) Reset() {
	*x = LiveRequest{}
	mi := &file_health_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveRequest) ProtoMessage() {}

func (x *LiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveRequest.ProtoReflect.Descriptor instead.
func (*LiveRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{11}
}

type LiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveResponse) Reset() {
	*x = LiveResponse{}
	mi := &file_health_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveResponse) ProtoMessage() {}

func (x *LiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveResponse.ProtoReflect.Descriptor instead.
func (*LiveResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{12}
}

func (x *LiveResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *LiveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_health_proto protoreflect.FileDescriptor

const file_health_proto_rawDesc = "" +
	"\n" +
	"\fhealth.proto\x12\x12manpasik.health.v1\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"P\n" +
	"\x13HealthCheckResponse\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.manpasik.health.v1.ServingStatusR\x06status\"\x99\x01\n" +
	"\x10GetStatusRequest\x12)\n" +
	"\x10include_metadata\x18\x01 \x01(\bR\x0fincludeMetadata\x121\n" +
	"\x14include_dependencies\x18\x02 \x01(\bR\x13includeDependencies\x12'\n" +
	"\x0finclude_metrics\x18\x03 \x01(\bR\x0eincludeMetrics\"\xa8\x03\n" +
	"\x11GetStatusResponse\x12B\n" +
	"\fservice_info\x18\x01 \x01(\v2\x1f.manpasik.health.v1.ServiceInfoR\vserviceInfo\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.manpasik.health.v1.ServingStatusR\x06status\x12O\n" +
	"\bmetadata\x18\x03 \x03(\v23.manpasik.health.v1.GetStatusResponse.MetadataEntryR\bmetadata\x12H\n" +
	"\fdependencies\x18\x04 \x03(\v2$.manpasik.health.v1.DependencyStatusR\fdependencies\x12<\n" +
	"\ametrics\x18\x05 \x01(\v2\".manpasik.health.v1.ServiceMetricsR\ametrics\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe2\x01\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"build_time\x18\x03 \x01(\tR\tbuildTime\x12!\n" +
	"\fbuild_commit\x18\x04 \x01(\tR\vbuildCommit\x12\x1d\n" +
	"\n" +
	"go_version\x18\x05 \x01(\tR\tgoVersion\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\tR\tstartedAt\x12%\n" +
	"\x0euptime_seconds\x18\a \x01(\x03R\ruptimeSeconds\"\xd5\x01\n" +
	"\x10DependencyStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\x04type\x18\x02 \x01(\x0e2\".manpasik.health.v1.DependencyTypeR\x04type\x12<\n" +
	"\x06health\x18\x03 \x01(\x0e2$.manpasik.health.v1.DependencyHealthR\x06health\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x02R\tlatencyMs\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x9a\x02\n" +
	"\x0eServiceMetrics\x12-\n" +
	"\x12active_connections\x18\x01 \x01(\x05R\x11activeConnections\x12)\n" +
	"\x10pending_requests\x18\x02 \x01(\x05R\x0fpendingRequests\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x03 \x01(\x02R\terrorRate\x12/\n" +
	"\x14avg_response_time_ms\x18\x04 \x01(\x02R\x11avgResponseTimeMs\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x03R\vmemoryBytes\x12\x1b\n" +
	"\tcpu_usage\x18\x06 \x01(\x02R\bcpuUsage\x12\x1e\n" +
	"\n" +
	"goroutines\x18\a \x01(\x05R\n" +
	"goroutines\"E\n" +
	"\x18CheckDependenciesRequest\x12)\n" +
	"\x10dependency_names\x18\x01 \x03(\tR\x0fdependencyNames\"\x86\x01\n" +
	"\x19CheckDependenciesResponse\x12\x1f\n" +
	"\vall_healthy\x18\x01 \x01(\bR\n" +
	"allHealthy\x12H\n" +
	"\fdependencies\x18\x02 \x03(\v2$.manpasik.health.v1.DependencyStatusR\fdependencies\"\x0e\n" +
	"\fReadyRequest\"?\n" +
	"\rReadyResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\r\n" +
	"\vLiveRequest\">\n" +
	"\fLiveResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x8b\x01\n" +
	"\rServingStatus\x12\x1a\n" +
	"\x16SERVING_STATUS_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16SERVING_STATUS_SERVING\x10\x01\x12\x1e\n" +
	"\x1aSERVING_STATUS_NOT_SERVING\x10\x02\x12\"\n" +
	"\x1eSERVING_STATUS_SERVICE_UNKNOWN\x10\x03*\xe8\x01\n" +
	"\x0eDependencyType\x12\x1b\n" +
	"\x17DEPENDENCY_TYPE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18DEPENDENCY_TYPE_DATABASE\x10\x01\x12\x19\n" +
	"\x15DEPENDENCY_TYPE_CACHE\x10\x02\x12!\n" +
	"\x1dDEPENDENCY_TYPE_MESSAGE_QUEUE\x10\x03\x12$\n" +
	" DEPENDENCY_TYPE_EXTERNAL_SERVICE\x10\x04\x12\x1b\n" +
	"\x17DEPENDENCY_TYPE_STORAGE\x10\x05\x12\x1a\n" +
	"\x16DEPENDENCY_TYPE_SEARCH\x10\x06*\x91\x01\n" +
	"\x10DependencyHealth\x12\x1d\n" +
	"\x19DEPENDENCY_HEALTH_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19DEPENDENCY_HEALTH_HEALTHY\x10\x01\x12\x1e\n" +
	"\x1aDEPENDENCY_HEALTH_DEGRADED\x10\x02\x12\x1f\n" +
	"\x1bDEPENDENCY_HEALTH_UNHEALTHY\x10\x032\xbe\x01\n" +
	"\x06Health\x12X\n" +
	"\x05Check\x12&.manpasik.health.v1.HealthCheckRequest\x1a'.manpasik.health.v1.HealthCheckResponse\x12Z\n" +
	"\x05Watch\x12&.manpasik.health.v1.HealthCheckRequest\x1a'.manpasik.health.v1.HealthCheckResponse0\x012\xf5\x02\n" +
	"\x0eExtendedHealth\x12X\n" +
	"\tGetStatus\x12$.manpasik.health.v1.GetStatusRequest\x1a%.manpasik.health.v1.GetStatusResponse\x12p\n" +
	"\x11CheckDependencies\x12,.manpasik.health.v1.CheckDependenciesRequest\x1a-.manpasik.health.v1.CheckDependenciesResponse\x12L\n" +
	"\x05Ready\x12 .manpasik.health.v1.ReadyRequest\x1a!.manpasik.health.v1.ReadyResponse\x12I\n" +
	"\x04Live\x12\x1f.manpasik.health.v1.LiveRequest\x1a .manpasik.health.v1.LiveResponseB4Z2github.com/manpasik/backend/shared/proto/health/v1b\x06proto3"

var (
	file_health_proto_rawDescOnce sync.Once
	file_health_proto_rawDescData []byte
)

func file_health_proto_rawDescGZIP() []byte {
	file_health_proto_rawDescOnce.Do(func() {
		file_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)))
	})
	return file_health_proto_rawDescData
}

var file_health_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_health_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_health_proto_goTypes = []any{
	(ServingStatus)(0),                // 0: manpasik.health.v1.ServingStatus
	(DependencyType)(0),               // 1: manpasik.health.v1.DependencyType
	(DependencyHealth)(0),             // 2: manpasik.health.v1.DependencyHealth
	(*HealthCheckRequest)(nil),        // 3: manpasik.health.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),       // 4: manpasik.health.v1.HealthCheckResponse
	(*GetStatusRequest)(nil),          // 5: manpasik.health.v1.GetStatusRequest
	(*GetStatusResponse)(nil),         // 6: manpasik.health.v1.GetStatusResponse
	(*ServiceInfo)(nil),               // 7: manpasik.health.v1.ServiceInfo
	(*DependencyStatus)(nil),          // 8: manpasik.health.v1.DependencyStatus
	(*ServiceMetrics)(nil),            // 9: manpasik.health.v1.ServiceMetrics
	(*CheckDependenciesRequest)(nil),  // 10: manpasik.health.v1.CheckDependenciesRequest
	(*CheckDependenciesResponse)(nil), // 11: manpasik.health.v1.CheckDependenciesResponse
	(*ReadyRequest)(nil),              // 12: manpasik.health.v1.ReadyRequest
	(*ReadyResponse)(nil),             // 13: manpasik.health.v1.ReadyResponse
	(*LiveRequest)(nil),               // 14: manpasik.health.v1.LiveRequest
	(*LiveResponse)(nil),              // 15: manpasik.health.v1.LiveResponse
	nil,                               // 16: manpasik.health.v1.GetStatusResponse.MetadataEntry
}
var file_health_proto_depIdxs = []int32{
	0,  // 0: manpasik.health.v1.HealthCheckResponse.status:type_name -> manpasik.health.v1.ServingStatus
	7,  // 1: manpasik.health.v1.GetStatusResponse.service_info:type_name -> manpasik.health.v1.ServiceInfo
	0,  // 2: manpasik.health.v1.GetStatusResponse.status:type_name -> manpasik.health.v1.ServingStatus
	16, // 3: manpasik.health.v1.GetStatusResponse.metadata:type_name -> manpasik.health.v1.GetStatusResponse.MetadataEntry
	8,  // 4: manpasik.health.v1.GetStatusResponse.dependencies:type_name -> manpasik.health.v1.DependencyStatus
	9,  // 5: manpasik.health.v1.GetStatusResponse.metrics:type_name -> manpasik.health.v1.ServiceMetrics
	1,  // 6: manpasik.health.v1.DependencyStatus.type:type_name -> manpasik.health.v1.DependencyType
	2,  // 7: manpasik.health.v1.DependencyStatus.health:type_name -> manpasik.health.v1.DependencyHealth
	8,  // 8: manpasik.health.v1.CheckDependenciesResponse.dependencies:type_name -> manpasik.health.v1.DependencyStatus
	3,  // 9: manpasik.health.v1.Health.Check:input_type -> manpasik.health.v1.HealthCheckRequest
	3,  // 10: manpasik.health.v1.Health.Watch:input_type -> manpasik.health.v1.HealthCheckRequest
	5,  // 11: manpasik.health.v1.ExtendedHealth.GetStatus:input_type -> manpasik.health.v1.GetStatusRequest
	10, // 12: manpasik.health.v1.ExtendedHealth.CheckDependencies:input_type -> manpasik.health.v1.CheckDependenciesRequest
	12, // 13: manpasik.health.v1.ExtendedHealth.Ready:input_type -> manpasik.health.v1.ReadyRequest
	14, // 14: manpasik.health.v1.ExtendedHealth.Live:input_type -> manpasik.health.v1.LiveRequest
	4,  // 15: manpasik.health.v1.Health.Check:output_type -> manpasik.health.v1.HealthCheckResponse
	4,  // 16: manpasik.health.v1.Health.Watch:output_type -> manpasik.health.v1.HealthCheckResponse
	6,  // 17: manpasik.health.v1.ExtendedHealth.GetStatus:output_type -> manpasik.health.v1.GetStatusResponse
	11, // 18: manpasik.health.v1.ExtendedHealth.CheckDependencies:output_type -> manpasik.health.v1.CheckDependenciesResponse
	13, // 19: manpasik.health.v1.ExtendedHealth.Ready:output_type -> manpasik.health.v1.ReadyResponse
	15, // 20: manpasik.health.v1.ExtendedHealth.Live:output_type -> manpasik.health.v1.LiveResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_health_proto_init() }
func file_health_proto_init() {
	if File_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_health_proto_goTypes,
		DependencyIndexes: file_health_proto_depIdxs,
		EnumInfos:         file_health_proto_enumTypes,
		MessageInfos:      file_health_proto_msgTypes,
	}.Build()
	File_health_proto = out.File
	file_health_proto_goTypes = nil
	file_health_proto_depIdxs = nil
}
