// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: proto/measurement.proto

package api_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MeasurementService_SyncMeasurements_FullMethodName     = "/manpasik.api.v1.MeasurementService/SyncMeasurements"
	MeasurementService_SubmitCheckupSession_FullMethodName = "/manpasik.api.v1.MeasurementService/SubmitCheckupSession"
)

// MeasurementServiceClient is the client API for MeasurementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeasurementServiceClient interface {
	// 측정 완료된 데이터를 중앙(클라우드)으로 오프라인 벌크 동기화 (CRDT)
	SyncMeasurements(ctx context.Context, in *SyncMeasurementsRequest, opts ...grpc.CallOption) (*SyncMeasurementsResponse, error)
	// v2.1: 패키지 종합 검진 결과 수집
	SubmitCheckupSession(ctx context.Context, in *SubmitCheckupRequest, opts ...grpc.CallOption) (*SubmitCheckupResponse, error)
}

type measurementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeasurementServiceClient(cc grpc.ClientConnInterface) MeasurementServiceClient {
	return &measurementServiceClient{cc}
}

func (c *measurementServiceClient) SyncMeasurements(ctx context.Context, in *SyncMeasurementsRequest, opts ...grpc.CallOption) (*SyncMeasurementsResponse, error) {
	out := new(SyncMeasurementsResponse)
	err := c.cc.Invoke(ctx, MeasurementService_SyncMeasurements_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *measurementServiceClient) SubmitCheckupSession(ctx context.Context, in *SubmitCheckupRequest, opts ...grpc.CallOption) (*SubmitCheckupResponse, error) {
	out := new(SubmitCheckupResponse)
	err := c.cc.Invoke(ctx, MeasurementService_SubmitCheckupSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeasurementServiceServer is the server API for MeasurementService service.
// All implementations must embed UnimplementedMeasurementServiceServer
// for forward compatibility
type MeasurementServiceServer interface {
	// 측정 완료된 데이터를 중앙(클라우드)으로 오프라인 벌크 동기화 (CRDT)
	SyncMeasurements(context.Context, *SyncMeasurementsRequest) (*SyncMeasurementsResponse, error)
	// v2.1: 패키지 종합 검진 결과 수집
	SubmitCheckupSession(context.Context, *SubmitCheckupRequest) (*SubmitCheckupResponse, error)
	mustEmbedUnimplementedMeasurementServiceServer()
}

// UnimplementedMeasurementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMeasurementServiceServer struct {
}

func (UnimplementedMeasurementServiceServer) SyncMeasurements(context.Context, *SyncMeasurementsRequest) (*SyncMeasurementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncMeasurements not implemented")
}
func (UnimplementedMeasurementServiceServer) SubmitCheckupSession(context.Context, *SubmitCheckupRequest) (*SubmitCheckupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitCheckupSession not implemented")
}
func (UnimplementedMeasurementServiceServer) mustEmbedUnimplementedMeasurementServiceServer() {}

// UnsafeMeasurementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeasurementServiceServer will
// result in compilation errors.
type UnsafeMeasurementServiceServer interface {
	mustEmbedUnimplementedMeasurementServiceServer()
}

func RegisterMeasurementServiceServer(s grpc.ServiceRegistrar, srv MeasurementServiceServer) {
	s.RegisterService(&MeasurementService_ServiceDesc, srv)
}

func _MeasurementService_SyncMeasurements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncMeasurementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeasurementServiceServer).SyncMeasurements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeasurementService_SyncMeasurements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeasurementServiceServer).SyncMeasurements(ctx, req.(*SyncMeasurementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeasurementService_SubmitCheckupSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCheckupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeasurementServiceServer).SubmitCheckupSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeasurementService_SubmitCheckupSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeasurementServiceServer).SubmitCheckupSession(ctx, req.(*SubmitCheckupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeasurementService_ServiceDesc is the grpc.ServiceDesc for MeasurementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeasurementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manpasik.api.v1.MeasurementService",
	HandlerType: (*MeasurementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncMeasurements",
			Handler:    _MeasurementService_SyncMeasurements_Handler,
		},
		{
			MethodName: "SubmitCheckupSession",
			Handler:    _MeasurementService_SubmitCheckupSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/measurement.proto",
}

const (
	ContextService_GetContextCards_FullMethodName = "/manpasik.api.v1.ContextService/GetContextCards"
)

// ContextServiceClient is the client API for ContextService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContextServiceClient interface {
	// v2.2: 사용자 상태를 분석하여 컨텍스트 카드 스트림 내려줌
	GetContextCards(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (ContextService_GetContextCardsClient, error)
}

type contextServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContextServiceClient(cc grpc.ClientConnInterface) ContextServiceClient {
	return &contextServiceClient{cc}
}

func (c *contextServiceClient) GetContextCards(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (ContextService_GetContextCardsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ContextService_ServiceDesc.Streams[0], ContextService_GetContextCards_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &contextServiceGetContextCardsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ContextService_GetContextCardsClient interface {
	Recv() (*ContextCardResponse, error)
	grpc.ClientStream
}

type contextServiceGetContextCardsClient struct {
	grpc.ClientStream
}

func (x *contextServiceGetContextCardsClient) Recv() (*ContextCardResponse, error) {
	m := new(ContextCardResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ContextServiceServer is the server API for ContextService service.
// All implementations must embed UnimplementedContextServiceServer
// for forward compatibility
type ContextServiceServer interface {
	// v2.2: 사용자 상태를 분석하여 컨텍스트 카드 스트림 내려줌
	GetContextCards(*ContextRequest, ContextService_GetContextCardsServer) error
	mustEmbedUnimplementedContextServiceServer()
}

// UnimplementedContextServiceServer must be embedded to have forward compatible implementations.
type UnimplementedContextServiceServer struct {
}

func (UnimplementedContextServiceServer) GetContextCards(*ContextRequest, ContextService_GetContextCardsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetContextCards not implemented")
}
func (UnimplementedContextServiceServer) mustEmbedUnimplementedContextServiceServer() {}

// UnsafeContextServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContextServiceServer will
// result in compilation errors.
type UnsafeContextServiceServer interface {
	mustEmbedUnimplementedContextServiceServer()
}

func RegisterContextServiceServer(s grpc.ServiceRegistrar, srv ContextServiceServer) {
	s.RegisterService(&ContextService_ServiceDesc, srv)
}

func _ContextService_GetContextCards_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ContextRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContextServiceServer).GetContextCards(m, &contextServiceGetContextCardsServer{stream})
}

type ContextService_GetContextCardsServer interface {
	Send(*ContextCardResponse) error
	grpc.ServerStream
}

type contextServiceGetContextCardsServer struct {
	grpc.ServerStream
}

func (x *contextServiceGetContextCardsServer) Send(m *ContextCardResponse) error {
	return x.ServerStream.SendMsg(m)
}

// ContextService_ServiceDesc is the grpc.ServiceDesc for ContextService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContextService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manpasik.api.v1.ContextService",
	HandlerType: (*ContextServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetContextCards",
			Handler:       _ContextService_GetContextCards_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/measurement.proto",
}

const (
	DiagnosticService_ReportSystemHealth_FullMethodName = "/manpasik.api.v1.DiagnosticService/ReportSystemHealth"
	DiagnosticService_ReportHealingEvent_FullMethodName = "/manpasik.api.v1.DiagnosticService/ReportHealingEvent"
)

// DiagnosticServiceClient is the client API for DiagnosticService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiagnosticServiceClient interface {
	// v2.3: 시스템 통합 건강 점수(L1~L6) 및 HwAlert 레포팅
	ReportSystemHealth(ctx context.Context, in *HealthReportRequest, opts ...grpc.CallOption) (*HealthReportResponse, error)
	// v2.4: 자가치유 결과 기록 (원격 에스컬레이션 티켓 연계용)
	ReportHealingEvent(ctx context.Context, in *HealingEventRequest, opts ...grpc.CallOption) (*HealingEventResponse, error)
}

type diagnosticServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiagnosticServiceClient(cc grpc.ClientConnInterface) DiagnosticServiceClient {
	return &diagnosticServiceClient{cc}
}

func (c *diagnosticServiceClient) ReportSystemHealth(ctx context.Context, in *HealthReportRequest, opts ...grpc.CallOption) (*HealthReportResponse, error) {
	out := new(HealthReportResponse)
	err := c.cc.Invoke(ctx, DiagnosticService_ReportSystemHealth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosticServiceClient) ReportHealingEvent(ctx context.Context, in *HealingEventRequest, opts ...grpc.CallOption) (*HealingEventResponse, error) {
	out := new(HealingEventResponse)
	err := c.cc.Invoke(ctx, DiagnosticService_ReportHealingEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiagnosticServiceServer is the server API for DiagnosticService service.
// All implementations must embed UnimplementedDiagnosticServiceServer
// for forward compatibility
type DiagnosticServiceServer interface {
	// v2.3: 시스템 통합 건강 점수(L1~L6) 및 HwAlert 레포팅
	ReportSystemHealth(context.Context, *HealthReportRequest) (*HealthReportResponse, error)
	// v2.4: 자가치유 결과 기록 (원격 에스컬레이션 티켓 연계용)
	ReportHealingEvent(context.Context, *HealingEventRequest) (*HealingEventResponse, error)
	mustEmbedUnimplementedDiagnosticServiceServer()
}

// UnimplementedDiagnosticServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDiagnosticServiceServer struct {
}

func (UnimplementedDiagnosticServiceServer) ReportSystemHealth(context.Context, *HealthReportRequest) (*HealthReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportSystemHealth not implemented")
}
func (UnimplementedDiagnosticServiceServer) ReportHealingEvent(context.Context, *HealingEventRequest) (*HealingEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportHealingEvent not implemented")
}
func (UnimplementedDiagnosticServiceServer) mustEmbedUnimplementedDiagnosticServiceServer() {}

// UnsafeDiagnosticServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiagnosticServiceServer will
// result in compilation errors.
type UnsafeDiagnosticServiceServer interface {
	mustEmbedUnimplementedDiagnosticServiceServer()
}

func RegisterDiagnosticServiceServer(s grpc.ServiceRegistrar, srv DiagnosticServiceServer) {
	s.RegisterService(&DiagnosticService_ServiceDesc, srv)
}

func _DiagnosticService_ReportSystemHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticServiceServer).ReportSystemHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagnosticService_ReportSystemHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticServiceServer).ReportSystemHealth(ctx, req.(*HealthReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnosticService_ReportHealingEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealingEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticServiceServer).ReportHealingEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagnosticService_ReportHealingEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticServiceServer).ReportHealingEvent(ctx, req.(*HealingEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiagnosticService_ServiceDesc is the grpc.ServiceDesc for DiagnosticService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiagnosticService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manpasik.api.v1.DiagnosticService",
	HandlerType: (*DiagnosticServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportSystemHealth",
			Handler:    _DiagnosticService_ReportSystemHealth_Handler,
		},
		{
			MethodName: "ReportHealingEvent",
			Handler:    _DiagnosticService_ReportHealingEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/measurement.proto",
}
